name: Bug Report
description: Report an issue with <Project Name>
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report!

  - type: textarea
    attributes:
      label: Description
      description: A brief description this bug
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: What was the process that led to this bug?
      value: |
        1.
        2.
        3.
        ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Result
      description: What did you expect to happen when following the steps to reproduce?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Result
      description: What actually happened?
    validations:
      required: true

  - type: input
    attributes:
      label: "<Project Name> Version"
      placeholder: "1.2.3"
    validations:
      required: true

  - type: input
    attributes:
      label: PHP Version
      placeholder: "7.4.x or 8.x.x"
    validations:
      required: true
